stages:
    - python_env
    - test

python_env:
    stage: python_env
    script:
        - virtualenv -p python3 venv3
        - source venv3/bin/activate
        - python -V
        - pip install --upgrade pip
        - mkdir tmp
        # There seems to be a weird bug with 1.14
        - TMPDIR=tmp/ pip install tensorflow==1.13.1
        - rm -r tmp
        - pip install -v .
    artifacts:
        paths:
            - venv3/
        expire_in: "2 hours"

test:
    stage: test
    script:
        - source venv3/bin/activate
        - cd tests
        - python -m unittest discover -v
