site_name: Deep Attention Sampling
repo_url: https://github.com/idiap/attention-sampling
theme: readthedocs
extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
extra_css:
    - css/extra.css
markdown_extensions:
    - mdx_math
nav:
    - Home: index.md
    - Installation: installation.md
    - Math and Architecture: attention-sampling.md
    - Keras API: keras-api.md
    - Custom Ops: custom-ops.md
    - Examples: examples.md
    - Contributing: contributing.md
